services:
  mariadb:
    image: mariadb:11.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: not-a-secret
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: not-a-secret
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mariadb_data:
  mongodb_data:
